# Generated by Django 5.0.3 on 2024-04-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, verbose_name='Роль')),
                ('salary', models.CharField(default='Договорная', max_length=20, verbose_name='Зарплата')),
                ('requirements', models.TextField(verbose_name='Требования')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Актульано')),
            ],
        ),
    ]
